export const dataOrderDetails = [
  {
    id: "1",
    order_id: "A-01",
    product_id: "ເບຍຫົວເສື້ອ",
    qty: "12",
    price: "200,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ລູກຄ້າສາຍໂຫດ",
    payment_method: "cash",
    payment_status: "pending",
    order_status: "ordered",
    reason: "ທົົດລອງ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "2",
    order_id: "A-02",
    product_id: "ບັດເປອງ",
    qty: "8",
    price: "150,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ບັດສົດໃສ",
    payment_method: "credit_card",
    payment_status: "paid",
    order_status: "success",
    reason: "ຄົງສົມບູນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "3",
    order_id: "A-03",
    product_id: "ສະລະດອນ",
    qty: "5",
    price: "100,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ສະລະດອນເປັນລັບ",
    payment_method: "cash",
    payment_status: "overdue",
    order_status: "pending",
    reason: "ສັດສເປິເຮັດບໍ່ສົມບູນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "4",
    order_id: "A-04",
    product_id: "ເບຍບົວສາຍ",
    qty: "15",
    price: "250,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ບອງມີກິ່ນ",
    payment_method: "credit_card",
    payment_status: "failed",
    order_status: "cancelled",
    reason: "ບໍ່ເຂົ້ມຮອບຜົນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "5",
    order_id: "A-05",
    product_id: "ເປອງສະບໍ່",
    qty: "20",
    price: "300,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ຄວາມໝາຍສົບໃສ",
    payment_method: "cash",
    payment_status: "cancelled",
    order_status: "separate_pay",
    reason: "ອອກບັດດອນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "6",
    order_id: "A-06",
    product_id: "ບັດເສື້ອງ",
    qty: "10",
    price: "180,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ສິ່ງປະເສີດສັດ",
    payment_method: "credit_card",
    payment_status: "pending",
    order_status: "ordered",
    reason: "ສັບສະກວດ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "7",
    order_id: "A-07",
    product_id: "ເບຍປະຈອນ",
    qty: "7",
    price: "130,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ປັບສະບູນຕົວເຂົ້ມ",
    payment_method: "cash",
    payment_status: "paid",
    order_status: "success",
    reason: "ອອກຄໍ່ອາລະ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "8",
    order_id: "A-08",
    product_id: "ບັດປອນ",
    qty: "14",
    price: "220,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ຄໍ່ຄວາມຈິງດີ",
    payment_method: "credit_card",
    payment_status: "overdue",
    order_status: "cancelled",
    reason: "ຄໍ່ຄວາມເຫັນແຮ່",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "9",
    order_id: "A-09",
    product_id: "ເບຍບັດ",
    qty: "9",
    price: "160,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ຄົບຄືນໃສ",
    payment_method: "cash",
    payment_status: "failed",
    order_status: "pending",
    reason: "ປົ່ນເປັນສົບ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "10",
    order_id: "A-10",
    product_id: "ສະບອງຈອບ",
    qty: "6",
    price: "120,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ວິເຕີກແລະຄໍ່",
    payment_method: "credit_card",
    payment_status: "paid",
    order_status: "success",
    reason: "ບັດສົດໃສ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "11",
    order_id: "A-11",
    product_id: "ເບຍປະຈອນມີກິ່ນ",
    qty: "13",
    price: "270,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ປະຈອນມີກິ່ນກັບຄວາມສະບັບສົດ",
    payment_method: "cash",
    payment_status: "pending",
    order_status: "ordered",
    reason: "ອອກບັດດອນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "12",
    order_id: "A-12",
    product_id: "ບັດປອນສົບເຂົ້ມ",
    qty: "11",
    price: "210,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ບັດປອນສົບເຂົ້ມກັບຄວາມສົດ",
    payment_method: "credit_card",
    payment_status: "paid",
    order_status: "success",
    reason: "ກິ່ນເປັນທົດລອງ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "13",
    order_id: "A-13",
    product_id: "ສະລະດອນອອກບັດ",
    qty: "16",
    price: "290,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ສະລະດອນອອກບັດມີຄວາມສົບ",
    payment_method: "cash",
    payment_status: "overdue",
    order_status: "pending",
    reason: "ບົດສະບັບບົດສະບັບ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "14",
    order_id: "A-14",
    product_id: "ບັດເສື້ອງສົບເຂົ້ມ",
    qty: "18",
    price: "320,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ສິ່ງປະເສີດທົດລອງ",
    payment_method: "credit_card",
    payment_status: "failed",
    order_status: "cancelled",
    reason: "ບໍ່ເຂົ້ມຮອບຜົນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "15",
    order_id: "A-15",
    product_id: "ເປອງສະບໍ່ກັບຄວາມປະເສີດ",
    qty: "22",
    price: "350,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ຄວາມປະເສີດສົບສຽງ",
    payment_method: "cash",
    payment_status: "pending",
    order_status: "separate_pay",
    reason: "ມີຄວາມບໍ່ສົມບູນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "16",
    order_id: "A-16",
    product_id: "ບັດເສື້ອງປອນ",
    qty: "12",
    price: "250,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ບັດສະບອງແລະຄືນ",
    payment_method: "credit_card",
    payment_status: "paid",
    order_status: "success",
    reason: "ຄວາມສົບສັບປອນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "17",
    order_id: "A-17",
    product_id: "ສະລະດອນຜົນສະບັບ",
    qty: "9",
    price: "180,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ບັດປະຈອນບໍ່ສົມບູນ",
    payment_method: "cash",
    payment_status: "overdue",
    order_status: "pending",
    reason: "ປົ່ນປົ່ນບັດ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "18",
    order_id: "A-18",
    product_id: "ບັດເສື້ອງປອນ",
    qty: "8",
    price: "150,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ຄວາມອອກບັດສະບັບ",
    payment_method: "credit_card",
    payment_status: "paid",
    order_status: "success",
    reason: "ປະສົມປົ່ນ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "19",
    order_id: "A-19",
    product_id: "ເປອງສະບໍ່ສົບ",
    qty: "11",
    price: "220,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ຄວາມປະເສີດສົບ",
    payment_method: "cash",
    payment_status: "cancelled",
    order_status: "separate_pay",
    reason: "ສະບັບແລະບັດ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
  {
    id: "20",
    order_id: "A-20",
    product_id: "ສະລະດອນສົບສຽງ",
    qty: "17",
    price: "280,000 LAK",
    total:"10,000,000 LAK"
 ,   comment: "ສະລະດອນເຄື່ອງເຂົ້ມ",
    payment_method: "credit_card",
    payment_status: "pending",
    order_status: "ordered",
    reason: "ຄົບຄືນໃສ",
    created_at: "08/08/2024",
    updated_at: "09/08/2024",
  },
];
