export const dataImportDetails = [
  {
    id: "1",
    import_id: "Beer",
    product_id: "A-456",
    qty: "10",
    purchase_price: "230,000 LAK",
    status: "success",
    description: "Test one",
    total: "12",
  },
  {
    id: "2",
    import_id: "Wine",
    product_id: "A-457",
    qty: "8",
    purchase_price: "320,000 LAK",
    status: "pending",
    description: "Test two",
    total: "15",
  },
  {
    id: "3",
    import_id: "Whiskey",
    product_id: "A-458",
    qty: "6",
    purchase_price: "450,000 LAK",
    status: "cancelled",
    description: "Test three",
    total: "10",
  },
  {
    id: "4",
    import_id: "Vodka",
    product_id: "A-459",
    qty: "12",
    purchase_price: "290,000 LAK",
    status: "success",
    description: "Test four",
    total: "14",
  },
  {
    id: "5",
    import_id: "Rum",
    product_id: "A-460",
    qty: "5",
    purchase_price: "400,000 LAK",
    status: "pending",
    description: "Test five",
    total: "8",
  },
  {
    id: "6",
    import_id: "Tequila",
    product_id: "A-461",
    qty: "9",
    purchase_price: "380,000 LAK",
    status: "cancelled",
    description: "Test six",
    total: "13",
  },
  {
    id: "7",
    import_id: "Gin",
    product_id: "A-462",
    qty: "7",
    purchase_price: "350,000 LAK",
    status: "success",
    description: "Test seven",
    total: "11",
  },
  {
    id: "8",
    import_id: "Brandy",
    product_id: "A-463",
    qty: "4",
    purchase_price: "420,000 LAK",
    status: "pending",
    description: "Test eight",
    total: "7",
  },
  {
    id: "9",
    import_id: "Champagne",
    product_id: "A-464",
    qty: "11",
    purchase_price: "550,000 LAK",
    status: "cancelled",
    description: "Test nine",
    total: "15",
  },
  {
    id: "10",
    import_id: "Cider",
    product_id: "A-465",
    qty: "13",
    purchase_price: "200,000 LAK",
    status: "success",
    description: "Test ten",
    total: "16",
  },
  {
    id: "11",
    import_id: "Sake",
    product_id: "A-466",
    qty: "14",
    purchase_price: "270,000 LAK",
    status: "pending",
    description: "Test eleven",
    total: "20",
  },
  {
    id: "12",
    import_id: "Absinthe",
    product_id: "A-467",
    qty: "15",
    purchase_price: "600,000 LAK",
    status: "cancelled",
    description: "Test twelve",
    total: "18",
  },
  {
    id: "13",
    import_id: "Mead",
    product_id: "A-468",
    qty: "3",
    purchase_price: "140,000 LAK",
    status: "success",
    description: "Test thirteen",
    total: "5",
  },
  {
    id: "14",
    import_id: "Ale",
    product_id: "A-469",
    qty: "16",
    purchase_price: "310,000 LAK",
    status: "pending",
    description: "Test fourteen",
    total: "22",
  },
  {
    id: "15",
    import_id: "Stout",
    product_id: "A-470",
    qty: "2",
    purchase_price: "480,000 LAK",
    status: "cancelled",
    description: "Test fifteen",
    total: "9",
  },
];
