export const dataInvoices = [
  {
    id: "1",
    created_by: "User1",
    updated_by: "User2",
    invoice_number: "2300",
    purchase_date: "09/08/2024",
    status: "success",
    description: "ກວດສອບສຳເລັດ",
    total: "10",
  },
  {
    id: "2",
    created_by: "User2",
    updated_by: "User3",
    invoice_number: "2301",
    purchase_date: "08/08/2024",
    status: "pending",
    description: "ກວດສອບຮອດເວລາ",
    total: "20",
  },
  {
    id: "3",
    created_by: "User3",
    updated_by: "User4",
    invoice_number: "2302",
    purchase_date: "07/08/2024",
    status: "cancelled",
    description: "ການຊຳລະບໍ່ສຳເລັດ",
    total: "30",
  },
  {
    id: "4",
    created_by: "User4",
    updated_by: "User5",
    invoice_number: "2303",
    purchase_date: "06/08/2024",
    status: "success",
    description: "ກວດສອບສຳເລັດ",
    total: "40",
  },
  {
    id: "5",
    created_by: "User5",
    updated_by: "User6",
    invoice_number: "2304",
    purchase_date: "05/08/2024",
    status: "pending",
    description: "ກວດສອບຮອດເວລາ",
    total: "50",
  },
  {
    id: "6",
    created_by: "User6",
    updated_by: "User7",
    invoice_number: "2305",
    purchase_date: "04/08/2024",
    status: "cancelled",
    description: "ການຊຳລະບໍ່ສຳເລັດ",
    total: "60",
  },
  {
    id: "7",
    created_by: "User7",
    updated_by: "User8",
    invoice_number: "2306",
    purchase_date: "03/08/2024",
    status: "success",
    description: "ກວດສອບສຳເລັດ",
    total: "70",
  },
  {
    id: "8",
    created_by: "User8",
    updated_by: "User9",
    invoice_number: "2307",
    purchase_date: "02/08/2024",
    status: "pending",
    description: "ກວດສອບຮອດເວລາ",
    total: "80",
  },
  {
    id: "9",
    created_by: "User9",
    updated_by: "User10",
    invoice_number: "2308",
    purchase_date: "01/08/2024",
    status: "cancelled",
    description: "ການຊຳລະບໍ່ສຳເລັດ",
    total: "90",
  },
  {
    id: "10",
    created_by: "User10",
    updated_by: "User11",
    invoice_number: "2309",
    purchase_date: "31/07/2024",
    status: "success",
    description: "ກວດສອບສຳເລັດ",
    total: "100",
  },
  {
    id: "11",
    created_by: "User11",
    updated_by: "User12",
    invoice_number: "2310",
    purchase_date: "30/07/2024",
    status: "pending",
    description: "ກວດສອບຮອດເວລາ",
    total: "110",
  },
  {
    id: "12",
    created_by: "User12",
    updated_by: "User13",
    invoice_number: "2311",
    purchase_date: "29/07/2024",
    status: "cancelled",
    description: "ການຊຳລະບໍ່ສຳເລັດ",
    total: "120",
  },
  {
    id: "13",
    created_by: "User13",
    updated_by: "User14",
    invoice_number: "2312",
    purchase_date: "28/07/2024",
    status: "success",
    description: "ກວດສອບສຳເລັດ",
    total: "130",
  },
  {
    id: "14",
    created_by: "User14",
    updated_by: "User15",
    invoice_number: "2313",
    purchase_date: "27/07/2024",
    status: "pending",
    description: "ກວດສອບຮອດເວລາ",
    total: "140",
  },
  {
    id: "15",
    created_by: "User15",
    updated_by: "User1",
    invoice_number: "2314",
    purchase_date: "26/07/2024",
    status: "cancelled",
    description: "ການຊຳລະບໍ່ສຳເລັດ",
    total: "150",
  },
];
