export const dataImportProduct = [
  {
    id: "1",
    invoice_id: "AC-45",
    import_number: "M-120",
    created_by: "User1",
    updated_by: "User2",
    imported_date: "08/09/2024",
    status: "success",
    description: "Test_1",
    total: "200",
  },
  {
    id: "2",
    invoice_id: "AC-46",
    import_number: "M-121",
    created_by: "User2",
    updated_by: "User3",
    imported_date: "07/09/2024",
    status: "pending",
    description: "Test_2",
    total: "150",
  },
  {
    id: "3",
    invoice_id: "AC-47",
    import_number: "M-122",
    created_by: "User3",
    updated_by: "User4",
    imported_date: "06/09/2024",
    status: "cancelled",
    description: "Test_3",
    total: "300",
  },
  {
    id: "4",
    invoice_id: "AC-48",
    import_number: "M-123",
    created_by: "User4",
    updated_by: "User5",
    imported_date: "05/09/2024",
    status: "success",
    description: "Test_4",
    total: "250",
  },
  {
    id: "5",
    invoice_id: "AC-49",
    import_number: "M-124",
    created_by: "User5",
    updated_by: "User6",
    imported_date: "04/09/2024",
    status: "pending",
    description: "Test_5",
    total: "100",
  },
  {
    id: "6",
    invoice_id: "AC-50",
    import_number: "M-125",
    created_by: "User6",
    updated_by: "User7",
    imported_date: "03/09/2024",
    status: "cancelled",
    description: "Test_6",
    total: "180",
  },
  {
    id: "7",
    invoice_id: "AC-51",
    import_number: "M-126",
    created_by: "User7",
    updated_by: "User8",
    imported_date: "02/09/2024",
    status: "success",
    description: "Test_7",
    total: "220",
  },
  {
    id: "8",
    invoice_id: "AC-52",
    import_number: "M-127",
    created_by: "User8",
    updated_by: "User9",
    imported_date: "01/09/2024",
    status: "pending",
    description: "Test_8",
    total: "160",
  },
  {
    id: "9",
    invoice_id: "AC-53",
    import_number: "M-128",
    created_by: "User9",
    updated_by: "User10",
    imported_date: "31/08/2024",
    status: "cancelled",
    description: "Test_9",
    total: "300",
  },
  {
    id: "10",
    invoice_id: "AC-54",
    import_number: "M-129",
    created_by: "User10",
    updated_by: "User11",
    imported_date: "30/08/2024",
    status: "success",
    description: "Test_10",
    total: "270",
  },
  {
    id: "11",
    invoice_id: "AC-55",
    import_number: "M-130",
    created_by: "User11",
    updated_by: "User12",
    imported_date: "29/08/2024",
    status: "pending",
    description: "Test_11",
    total: "230",
  },
  {
    id: "12",
    invoice_id: "AC-56",
    import_number: "M-131",
    created_by: "User12",
    updated_by: "User13",
    imported_date: "28/08/2024",
    status: "cancelled",
    description: "Test_12",
    total: "190",
  },
  {
    id: "13",
    invoice_id: "AC-57",
    import_number: "M-132",
    created_by: "User13",
    updated_by: "User14",
    imported_date: "27/08/2024",
    status: "success",
    description: "Test_13",
    total: "240",
  },
  {
    id: "14",
    invoice_id: "AC-58",
    import_number: "M-133",
    created_by: "User14",
    updated_by: "User15",
    imported_date: "26/08/2024",
    status: "pending",
    description: "Test_14",
    total: "200",
  },
  {
    id: "15",
    invoice_id: "AC-59",
    import_number: "M-134",
    created_by: "User15",
    updated_by: "User1",
    imported_date: "25/08/2024",
    status: "cancelled",
    description: "Test_15",
    total: "150",
  },
];
