export const dataInvoiceDetails = [
  {
    id: "1",
    invoice_id: "A-001",
    product_id: "Beer",
    qty: "12",
    purchase_price: "240,000 LAK",
    status: "success",
    description: "Test_1",
    total: "300,000 LAK",
  },
  {
    id: "2",
    invoice_id: "A-002",
    product_id: "Wine",
    qty: "8",
    purchase_price: "480,000 LAK",
    status: "pending",
    description: "Test_2",
    total: "500,000 LAK",
  },
  {
    id: "3",
    invoice_id: "A-003",
    product_id: "Whiskey",
    qty: "5",
    purchase_price: "1,200,000 LAK",
    status: "cancelled",
    description: "Test_3",
    total: "1,250,000 LAK",
  },
  {
    id: "4",
    invoice_id: "A-004",
    product_id: "Vodka",
    qty: "10",
    purchase_price: "600,000 LAK",
    status: "success",
    description: "Test_4",
    total: "650,000 LAK",
  },
  {
    id: "5",
    invoice_id: "A-005",
    product_id: "Rum",
    qty: "7",
    purchase_price: "350,000 LAK",
    status: "pending",
    description: "Test_5",
    total: "400,000 LAK",
  },
  {
    id: "6",
    invoice_id: "A-006",
    product_id: "Tequila",
    qty: "6",
    purchase_price: "900,000 LAK",
    status: "cancelled",
    description: "Test_6",
    total: "950,000 LAK",
  },
  {
    id: "7",
    invoice_id: "A-007",
    product_id: "Gin",
    qty: "9",
    purchase_price: "270,000 LAK",
    status: "success",
    description: "Test_7",
    total: "320,000 LAK",
  },
  {
    id: "8",
    invoice_id: "A-008",
    product_id: "Brandy",
    qty: "11",
    purchase_price: "330,000 LAK",
    status: "pending",
    description: "Test_8",
    total: "380,000 LAK",
  },
  {
    id: "9",
    invoice_id: "A-009",
    product_id: "Champagne",
    qty: "3",
    purchase_price: "1,500,000 LAK",
    status: "cancelled",
    description: "Test_9",
    total: "1,600,000 LAK",
  },
  {
    id: "10",
    invoice_id: "A-010",
    product_id: "Cider",
    qty: "14",
    purchase_price: "210,000 LAK",
    status: "success",
    description: "Test_10",
    total: "250,000 LAK",
  },
  {
    id: "11",
    invoice_id: "A-011",
    product_id: "Sake",
    qty: "15",
    purchase_price: "450,000 LAK",
    status: "pending",
    description: "Test_11",
    total: "500,000 LAK",
  },
  {
    id: "12",
    invoice_id: "A-012",
    product_id: "Absinthe",
    qty: "4",
    purchase_price: "800,000 LAK",
    status: "cancelled",
    description: "Test_12",
    total: "850,000 LAK",
  },
  {
    id: "13",
    invoice_id: "A-013",
    product_id: "Mead",
    qty: "13",
    purchase_price: "520,000 LAK",
    status: "success",
    description: "Test_13",
    total: "570,000 LAK",
  },
  {
    id: "14",
    invoice_id: "A-014",
    product_id: "Ale",
    qty: "16",
    purchase_price: "320,000 LAK",
    status: "pending",
    description: "Test_14",
    total: "370,000 LAK",
  },
  {
    id: "15",
    invoice_id: "A-015",
    product_id: "Stout",
    qty: "18",
    purchase_price: "720,000 LAK",
    status: "cancelled",
    description: "Test_15",
    total: "800,000 LAK",
  },
];
